"""Build the small satellite map from Natural Earth's public-domain 110m land."""
import json
from pathlib import Path
import requests

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson'

def main():
    response = requests.get(SOURCE, timeout=30)
    response.raise_for_status()
    paths = []
    for feature in response.json()['features']:
        geometry = feature['geometry']
        polygons = geometry['coordinates'] if geometry['type'] == 'MultiPolygon' else [geometry['coordinates']]
        for polygon in polygons:
            paths.append(''.join(''.join(
                f'{"M" if i == 0 else "L"}{150 + lon / 180 * 133:.2f},{94 - lat / 90 * 70:.2f}'
                for i, (lon, lat) in enumerate(ring)
            ) + 'Z' for ring in polygon))
    target = ROOT / 'src/earth-land.ts'
    target.write_text('// Generated by scripts/build_earth_land.py. Natural Earth, public domain.\n'
                      + 'export const earthLand = ' + json.dumps(paths, separators=(',', ':')) + ';\n')
    print(f'{len(paths)} land polygons, {target.stat().st_size} bytes')

if __name__ == '__main__':
    main()
